version: '3'
services:

        wordpress:
                build: ./wordpress
                restart: always
                container_name: wordpress
                hostname: wordpress
                environment:
                        WORDPRESS_DB_HOST: mysql:3306
                        WORDPRESS_DB_USER: root
                        WORDPRESS_DB_PASSWORD: rootpassword
                        WORDPRESS_DB_NAME: wordpress
                        WORDPRESS_TABLE_PREFIX: wp_
                        WORDPRESS_DEBUG: 1

      #          command: gunicorn wordpress:wordpress -b :9000 --name app --log-level=debug --log-file=-
                depends_on:
                        - db
                ports:
                        - 9000:9000
                networks:
                        - frontend
                        - backend

        db:
                image: mysql:5.7
                restart: always
                hostname: mysql
                container_name: db
                environment:
                        MYSQL_DATABASE: wordpress
                        MYSQL_USER: root
                        MYSQL_PASSWORD: rootpassword
                        MYSQL_RANDOM_ROOT_PASSWORD: '1'
                
                ports:
                        - 3306:3306
                networks:
                        - backend
        
        web:
                
                build: ./nginx
                container_name: web
                ports:
                        - 80:80
                        - 443:443
                
                depends_on:
                        - db
                        - wordpress
                networks:
                        - frontend


networks:
      frontend:
        driver: bridge
      backend:
        driver: bridge
       


   