version: '3'
services:
    
  wordpress:
      build: ./wordpress
      restart: always
      container_name: wordpress
      hostname: wordpress
      volumes:
         - ./wordpress/wp:/var/www/html
      environment:
         WORDPRESS_DB_HOST: db
         WORDPRESS_DB_USER: wordpress
         WORDPRESS_DB_PASSWORD: wordpress
         WORDPRESS_DB_NAME: wordpress
      depends_on:
         - db
      ports:
         - 9000:9000
      networks:
         - frontend
         - backend

        
  db:
      build: ./db
      restart: always
      container_name: db
      hostname: db
      command: --default-authentication-plugin=mysql_native_password
      volumes:
         - ./db/data:/var/lib/mysql
      environment:
         MYSQL_DATABASE: wordpress
         MYSQL_USER: wordpress
         MYSQL_PASSWORD: wordpress
         MYSQL_ROOT_PASSWORD: wordpress
      ports:
         - 3306:3306
      networks:
         - backend
         - frontend  

  
  web:
      build: ./nginx
      container_name: web
      volumes:
         - ./wordpress/wp:/var/www/html
         - ./nginx/default.conf:/etc/nginx/conf.d/default.conf                
      depends_on:
         - db
         - wordpress
      ports:
         - 80:80
         - 443:443
      networks:
         - frontend
         - backend 

networks:
      frontend:
         driver: bridge
      backend:
         driver: bridge
